##
## Makefile for Makefile in /home/leroy_0/rendu/J12
## 
## Made by maxime leroy
## Login   <leroy_0@epitech.net>
## 
## Started on  Tue Oct 13 18:35:40 2015 maxime leroy
## Last update Wed Oct 14 17:59:00 2015 maxime leroy
##

NAME	= cat

SRC	= cat.c

all:	$(NAME)

$(NAME):
	cc -I ~/lib/ -o $(NAME) $(SRC)

clean:
	rm -f $(NAME)

fclean:		clean
	rm -f $(NAME)

re:	fclean clean

.PHONY: all clean fclean re
